# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: I. A. Galdames
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  <p>I. A. Galdames, escritor chileno de ciencia ficción nacido en 1987. Es un desarrollador web autodidacta y una mermelada de ayer.</p>

  <p>Ha publicado cuentos en la antología Neon Dreams and Nightmares, la revista Espejo Humeante, en la revista Anapoyesis, la revista Axioma, en Teoría Omicrón, la revista Penumbria,  la revista Iguales, El ojo de Uk, Weird Review y la reconocida revista Axxón.</p>

  <p>Certificado en escritura creativa como alumno de Brandon Sanderson, además tiene un Diplomado en Storytelling y un certificado profesional en Escritura Creativa de Videojuegos por University of British Columbia.</p>

  <p>Sus escritos son mayormente de ciencia ficción y exploran la soledad, el aislamiento, la percepción temporal y el existencialismo, con inspiraciones expresionistas, cyberpunk y neo-noir.</p>

  <p>Su primer libro, Corceles Azules, es una antología fix-up cyberpunk. También participó en la antología CyberTerror: Austral.</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ignaciogaldames.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - node_modules
  - webpack.config.js
  - package.json
  - package-lock.json
  - assets/js
  - assets/scss

include:
  - assets/js/bundle.js
  - assets/css/main.css

collections:
  libros:
    output: true
    
kramdown:
  syntax_highlighter_opts:
    disable: true
